Layout Component added
aliturab99/managie pull request #1
Opened 2024-04-19 21:29 UTC by aliturab99

2024-04-19 21:32 UTC, ServilancerOfficial requested changes
Please make sure not to make these changes

2024-04-19 21:32 UTC, ServilancerOfficial commented on dashboard/src/App.css
> +  background-color: #124b66 !important;
Add this to Variable Please

2024-04-19 21:32 UTC, ServilancerOfficial commented on dashboard/src/App.css
> +
Remove Extra Line

2024-04-19 21:32 UTC, ServilancerOfficial commented on dashboard/src/index.js
> +
Remove Extra Line

2024-04-20 10:56 UTC, aliturab99 commented on dashboard/src/App.css
> +
Resolved

2024-04-20 10:57 UTC, aliturab99 commented on dashboard/src/App.css
> +
Resolved

2024-04-20 10:57 UTC, aliturab99 commented on dashboard/src/index.js
> +
Removed

2024-04-20 11:05 UTC, aliturab99 commented on dashboard/src/App.css
> +  background-color: #124b66 !important;
added

2024-04-20 11:06 UTC, merged